fix(resource-linking): disallow if start event parent not process
camunda/improved-canvas pull request #75
Opened 2024-09-19 13:42 UTC by philippfromme

Linking a form to a start event is only possible if the parent is a process.

![brave_3X1FrM5adm](https://github.com/user-attachments/assets/175a4e5e-d8fb-45ce-87d2-8747c4056ea8)

2024-09-19 14:30 UTC, barmac requested changes
Form linking works just fine in a participant, so it should be available there too
<img width="577" alt="image" src="https://github.com/user-attachments/assets/4ecfb26c-a05c-4da3-b545-865e1f72b612">

2024-09-19 14:53 UTC, philippfromme commented
@barmac Ooops.

2024-09-19 15:01 UTC, philippfromme commented
@barmac Fixed.

2024-09-20 11:08 UTC, barmac approved these changes

2024-09-20 11:13 UTC, merged